Chore/vue27
org-nexus-projects/ufabc-next-extension pull request #77
Opened 2024-08-16 01:13 UTC by Joabesv

2024-09-19 23:00 UTC, mateusbrg commented on src/components/Modal.vue
> +  }
o que é isso kkkkkkk

2024-09-19 23:02 UTC, mateusbrg commented on src/components/Modal.vue
> +const oldComponentObject = computed(() => convertDisciplina(component))
fix
```suggestion
const oldComponentObject = computed(() => convertDisciplina(component.value))
```

2024-09-19 23:06 UTC, mateusbrg commented on src/components/Modal.vue
> +        console.log('deu nao pai');
deu nao :(

2024-09-19 23:10 UTC, mateusbrg commented on src/components/Modal.vue
> +  if (rowIndex <= computeKicksForecast) {
Aqui vai quebrar mestre

2024-09-19 23:10 UTC, mateusbrg commented on src/components/Modal.vue
> +  if (rowIndex >= component.vagas) {
fix
```suggestion
  if (rowIndex >= component.value.vagas) {
```

2024-09-20 00:06 UTC, mateusbrg requested changes
só altera lá fé

2024-09-20 00:08 UTC, Joabesv commented on src/components/Modal.vue
> +  }
old code secret

2024-09-21 14:12 UTC, merged